### ISSUE TITLE
api-url is null

### ISSUE THREAD

**Issue by tomasz-galazka** [hourliert/rest-service#1]
It doesn`t work for me. I allways get null in request url host section. Also I found that demo files are diffrent on sample page and demo source.

**Comment by hourliert** [comment]
Thanks for the report.
I check this when I have time in 2 days.

**Comment by hourliert** [comment]
Hi,
I updated the demo with this https://github.com/hourliert/rest-service/commit/6689a439dffd8e77009bc7645111604ca1af04fc . I hope it will help you.

Tell me if I can close this issue.
